# Generated by Django 2.1 on 2018-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180904_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(default='defualt.png', upload_to=''),
        ),
    ]
