# Generated by Django 2.1.1 on 2019-01-17 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180907_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placestatus',
            options={'verbose_name_plural': 'Place statuses'},
        ),
        migrations.AlterField(
            model_name='image',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Trip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag'),
        ),
    ]
