# Generated by Django 2.1.1 on 2019-01-23 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20190122_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
