# Generated by Django 2.1.1 on 2019-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190123_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.Image'),
        ),
        migrations.AlterField(
            model_name='place',
            name='trip',
            field=models.ManyToManyField(blank=True, to='blog.Trip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.ManyToManyField(blank=True, to='blog.Place'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
