# Generated by Django 2.1.1 on 2019-02-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
